import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Descendant } from "slate";
import { MarkdownEditor } from "../components/editor";
import { ElementTypes } from "../types/document";

const Home: NextPage = () => {
  const [document, updateDocument] = useState<Descendant[]>([
    {
      type: ElementTypes.paragraph,
      children: [
        {
          text: "Hello World!",
        },
      ],
    },
  ]);
  return (
    <div className="w-screen h-screen flex flex-row">
      <Head>
        <title>Markdown driven blog writer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-3/4 mx-auto my-32 "
      onClick={() => {}}>
      <MarkdownEditor
        document={document}
      ></MarkdownEditor>
      </div>
    </div>
  );
};

export default Home;
